src/extensions/table.js
test/extensions/table/basic-alignment.html
test/extensions/table/basic-alignment.md

Currently the rendering of tables breaks if the header contains alignment symbols (":"). This does not add alignment support but merely prevents the rendering from breaking altogether. Also see #129.

Do not break on alignment characters in headers

---

src/showdown.js
test/cases/html5-strutural-tags.html
test/cases/html5-strutural-tags.md

(#140 redone against develop)
fixes #90 
This is the fix we're using in Ghost to add support for additional HTML5 elements. Thought I'd send it over as [requested](https://github.com/showdownjs/showdown/issues/90#issuecomment-70543134)

Add missing block elements

---

src/showdown.js

(#141 redone against develop)
With the current code, anytime you specify a plugin by string name, and it cannot be loaded you get the error message 
> Extension 'undefined' could not be loaded.  It was either not found or is not a valid extension.
It always says undefined, because `plugin` has already been overwritten.
This small change makes sure you get the string name.

Fix extension name in error always 'undefined'

---

package.json

Hello
According to showdown's [license.txt](https://github.com/showdownjs/showdown/blob/master/license.txt), I think showdown is under the [`BSD-3-Clause`](https://opensource.org/licenses/BSD-3-Clause) license.

update license field in package.json

---

src/subParsers/lists.js

Certain utilities including [vimwiki ](https://github.com/vimwiki/vimwiki) generate checkboxes using the capital [X]. This change adds support for either x or X within checkboxes.

Support for case-insensitive checkboxes for render. [x] == [X]

---

README.md
src/options.js
src/subParsers/italicsAndBold.js
test/features/enable-literalMidWordAsterisks.html
test/features/enable-literalMidWordAsterisks.md
test/node/testsuite.features.js

Hi there,
I thought I would implement a slightly new feature similar to ignoring midword underscores but with asterisks. The main use case is ignoring cursing :) such as
```
This is a f**king useless word
That guy is a m*th*rf*ck**g m*r*n 
```
Well, you get the point.
I've also added some tests:
```
makeHtml() features testsuite
issues
✓ enable literalMidWordAsterisks
359 passing (321ms)
Running "clean:0" (clean) task
>> 1 path cleaned.
Done.
```
Tell me if there's anything else I should do. Thanks!

New option for mid word asterisks

---

src/subParsers/images.js
src/subParsers/stripLinkDefinitions.js

Hi,
I have a markdown file like this:
```markdown
This is a [link][].
[link]: https://en.wikipedia.org/wiki/Textile_(markup_language) "Textile"
```
This is a real link, but the convert result is:
```html
<p>This is a <a href="https://en.wikipedia.org/wiki/Textile_" title="markup_language) &quot;Textile">link</a>.</p>
```
The same problem also affects inline image syntax. I tried to fix it, since javascript regular expression doesn't support lookbehind syntax, So I modified the URL match to greedily, it should be no side effects for other code, `grunt test` is passed.

fix brackets in link URL

---

src/helpers.js

Reason being a.constructor === Array is always falsey when you run showdown within Node's VM API.
Related:
https://github.com/nodejs/node/issues/7351

Replace a.constructor === Array with Array.isArray(a)

---

src/loader.js

Because of the ordering of the loader, it's not possible use define.amd within a Node environment.  While this isn't a very popular use-case, it's possible to use define.amd inside Node.
This will eliminate the need for my hack to make showdown always force the module.exports expression to be falsey: https://github.com/gcollazo/ember-cli-showdown/blob/master/index.js#L55-L56 in order to allow showdown to work with Ember's loader within Node (for server-side rendering).

Allow use of AMD loader to be used within Node env

---

README.md

No space after ':' creates problem with Boldness of 'tasklists' and description in Wiki

Sanitize README.md

---

package.json

This PR simply adds a _files_ field to the _package.json_ so that the size of the published package is reduced by only including the files required (the _bin_ and the _dist_ folders).
Before: https://packagephobia.now.sh/result?p=showdown _(All files from this repository included)_
After:
```sh
$ npm publish --dry
npm notice
npm notice package: showdown@2.0.0-alpha1
npm notice === Tarball Contents ===
npm notice 1.6kB   package.json
npm notice 37.4kB  CHANGELOG.md
npm notice 1.1kB   LICENSE
npm notice 18.8kB  README.md
npm notice 47B     bin/showdown.js
npm notice 173.5kB dist/showdown.js
npm notice 489.0kB dist/showdown.js.map
npm notice 81.1kB  dist/showdown.min.js
npm notice 91.9kB  dist/showdown.min.js.map
npm notice === Tarball Details ===
npm notice name:          showdown
npm …
```

Reduce the size of the published package

---

README.md

Fixes minor issue in the documentation.

Escaped the <br> in README.md

---

src/subParsers/makehtml/links.js
test/functional/makehtml/cases/features/#379.openLinksInNewWindow-breaks-em-markdup.html
test/functional/makehtml/cases/features/openLinksInNewWindow/simple-cases.html
test/functional/makehtml/cases/features/openLinksInNewWindow/simple.html
test/functional/makehtml/cases/features/openLinksInNewWindow/simplifiedAutoLink.html

Not sure how well this fits in with your goals for the project, but my understanding is that using `target="_blank"` without also adding `rel="noopener noreferrer"` creates a vulnerability (since the site you're linking to has access to the `window.opener` by default. This pull adds `rel="noopener noreferrer"` to links generated by the `makeHtml` converter when `openLinksInNewWindow` is `true`.
Let me know if I dun goofed or if I can do anything else to help. Thanks for making Showdown!

Add rel="noopener noreferrer" to links when openLinksInNewWindow is on.

---

package.json
src/subParsers/makemarkdown/break.js
src/subParsers/makemarkdown/node.js
test/functional/makemarkdown/cases/standard/breaks.html
test/functional/makemarkdown/cases/standard/breaks.md

the old link (https://assets-cdn.github.com/images/icons/emoji/octocat.png) will return 404. I have replaced it with the new location for this emoji (https://github.githubassets.com/images/icons/emoji/octocat.png?v8)
Old location:
New location:

fix: octocat emoji image location

---

package-lock.json
package.json

This fixes the mem security vulnerability (https://github.com/jimmyleray/Emendare/issues/584).
The vulnerability only presents itself when showdown is used as a CLI; it is unlikely that this would have been exploitable.

Update yargs to 14.2.0

---

src/helpers.js
src/options.js
src/subParsers/makehtml/images.js
src/subParsers/makehtml/links.js
src/subParsers/makehtml/stripLinkDefinitions.js
test/functional/makehtml/cases/features/relativePathBaseUrl.html
test/functional/makehtml/cases/features/relativePathBaseUrl.md
test/functional/makehtml/testsuite.features.js

This feature enables support for prepending a base URL to relative paths in
links and images when converting Markdown to HTML.
Closes #536

feat(relativePathBaseUrl): Add support for prepending a base URL

---

src/subParsers/makehtml/hashHTMLBlocks.js
test/functional/makehtml/cases/standard/html5-strutural-tags.html
test/functional/makehtml/cases/standard/html5-strutural-tags.md
test/functional/makemarkdown/cases/standard/html5-strutural-tags.html
test/functional/makemarkdown/cases/standard/html5-strutural-tags.md

Include HTML5.1 <details> in known block tags

---

src/subParsers/makehtml/stripLinkDefinitions.js
test/functional/makehtml/cases/issues/reference-link-impostors.html
test/functional/makehtml/cases/issues/reference-link-impostors.md

This change fixes an issue where we entirely strip out text that may be erroneously detected to be a link definition.  Without these changes, `converter.makeHtml('[Jim] said to [him]: Ahoy!')` returns an empty string.
To address this, we add two constraints when detecting link definitions...
1) Tighter regex matching the content of the square brackets.  Instead of `[(.+)]` we make sure the contents of the square brackets doesn't include square brackets with `[([^\]])`.  Otherwise for example with input `[a] [b] [c]` we match `a] [b] [c` as the linkId.
2) Back out if there are not two occurrences of the detected link id, since if there is no previous occurrence, it must not be a link definition.

fix link definition impostors

---

src/subParsers/makehtml/lists.js
test/functional/makehtml/cases/features/#164.4.tasklists.html
test/functional/makehtml/cases/features/#164.4.tasklists.md

GFM requires a whitespace between brackets for tasklists.
Lists with empty brackets at the beginning shouldn't be converted to tasklists.
Closes #655

fix(lists): Fix tasklists to comply with GFM

---

src/subParsers/makemarkdown/table.js

fix for html columns align right. currently hmtl cols
with align right get converted to md with align center
e.g. html
`<th style="text-align: right">head</th>`
get converted to
`:---: (suddenly center)`
this pull request fixes that bug
Closes #689

fix(makemarkdown.table): col text align right

---

src/helpers.js

Similar to my last PR, I ported this library to TypeScript (https://github.com/dennisss/showdown/tree/ts) targeted at the claimed ES3 compatibility of this library.
Found that String.prototype.repeat (ES6) is used in the polyfill for String.prototype.padEnd, so both polyfills are needed to support ES3

fix(polyfill) String.prototype.repeat

---

.github/workflows/docs.yml

With this update, the documentation flow will be triggered only for the `master` branch when there are changes in the:
- `mkdocs.yml` file
- `.github/workflows/docs.yml` workflow file
- `docs` folder

docs: updated triggers for the documentation flow

---

docs/assets/extra.css
mkdocs.yml

Theme color and accent (hover) color:

docs: added 'corporate' colors for docs

---

test/functional/makehtml/testsuite.features.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

src/subParsers/makemarkdown/image.js

when <img src="a" width="auto" height="auto" /> then ![null](<a> =autoxauto)
after fix ![null](<a> =*x*)

fix bug width|height = auto

---

Gruntfile.js
package-lock.json
package.json
test/functional/makehtml/cases/commonmark.testsuite.json
test/functional/makehtml/makehtml.bootstrap.js
test/functional/makehtml/testsuite.commonmark.js

Hey folks 👋 I'm opening this PR to try to open a conversation about supporting the CommonMark spec. I know by running these tests that there is a **long** way to go with some of these edge-cases but I thought I would open up the conversation at least 👍 
This is mostly continuing on from conversations like https://github.com/showdownjs/showdown/issues/620 just now a few years later when the wider community has moved forward a little bit

Add updated CommonMark Tests

---

src/subParsers/makehtml/heading.js
test/functional/makehtml/cases/features/#320.github-compatible-generated-header-id.html
test/functional/makehtml/cases/features/#320.github-compatible-generated-header-id.md

fix(subParsers): strip international punctuation from github headers
